import java.util.*;

public class CryptoA1LetterFreq {
	public static void main(String [] args) {
		String s = "SFGESUAXXVUASVOOHKASUEGEOHDXNR"+
		"COCORMSHKGEOPARSHGOLGXFGEOFSCU"+
		"GRUUSKHWOHGSHXNCFRAAUOWOUGOCBC"+
		"DPGXKCRPEDBXNCUOGESURUUSKHWOHG"+
		"QRUPXUGOMXHGNOUMRDXHGEOOSKEGEW"+
		"XHGERHMXHGEOGESCGSOGEMRDSHGEOD"+
		"ORCGQXGEXNURHMRHMUSLGOOHRUDXNE"+
		"RZOMSUBXZOCOMFCXWBCRBVSHKGESUR"+
		"UUSKHWOHGSGQRUOHBCDPGOMNUSHKRU"+
		"SWPAOWXHXRAPERJOGSBUNJUGSGNGSX"+
		"HBSPEOCFXCGESURUUSKHWOHGUNJWSG"+
		"GEOFXAAXQSHKSGOWUJDOWRSAQSGESH"+
		"RWXHGEXFGEOCOAORUOMRGOXFGESURU"+
		"USKHWOHGFSCUGPCXZSMOGEOUNJUGSG"+
		"NGSXHGRJAONUOMFXCGEOAOGGOCUPCO"+
		"UOHGSHGEOPARSHGOLGUOBXHMMOUBCS"+
		"JORHMSWPAOWOHGDXNCXQHBSPEOCUDU"+
		"GOWFXCOHBCDPGSHKRHMMOBCDPGSHKG"+
		"OLGFSAOUDXNWRDNUOUXWOXFGEOXGEO"+
		"CUNJUGSGNGSXHBSPEOCUVHXQHSHGEO"+
		"ASGOCRGNCODXNWRDQXCVSHKCXNPUXF"+
		"GQXRHMWRDNUORHDPCXKCRWWSHKARHK"+
		"NRKOXFDXNCBEXSBO";
		HashMap<Character, Integer> cO = new HashMap<Character, Integer>();
		for (int i = 0; i < s.length(); i++) {
			if (!cO.containsKey(s.charAt(i))) {
				cO.put(s.charAt(i), 0);
			}
			cO.put(s.charAt(i), cO.get(s.charAt(i))+1);
		}

		for (Character c : cO.keySet()) {
			System.out.println(c + ": " + ((double)cO.get(c))/s.length());
		}
	}
}
